config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'searches#index'
  get '/searches/get_ajx', to: 'searches#get_ajx'
  get '/searches/get_ajx_item_infos', to: 'searches#get_ajx_item_infos'
  resources :searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
   
    can :read, :all                   # allow everyone to read everything
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      if user.role? :superadmin
        can :manage, :all             # allow superadmins to do anything
      elsif user.role? :manager
        can :manage, [User, Product]  # allow managers to do anything to products and users
      elsif user.role? :sales
        can :update, Product, :hidden => false  # allow sales to only update visible products
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  self.table_name = 'Categories'
  self.primary_key =  'category_id'

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/city.rb
class City < ApplicationRecord
  self.table_name = 'Cities'
  self.primary_key =  'city_id'

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/item.rb
class Item < ApplicationRecord
  self.table_name = 'Items'
  self.primary_key =  'item_id'

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable
end

app/models/mailing_list.rb
class MailingList < ApplicationRecord
  self.table_name = 'mailing_list'
  self.primary_key =  'user_id'
end

app/models/recycling_plant.rb
class RecyclingPlant < ApplicationRecord
  self.table_name = 'recycling_plants'
  self.primary_key =  'plant_id'

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/search.rb
# Search attributes:
# text:string 
# zip:string 
# slug:string:uniq

class Search < ApplicationRecord
	extend FriendlyId
	friendly_id :text, use: :slugged
	def should_generate_new_friendly_id?
		text_changed?
	end
end

app/models/search_category.rb
class SearchCategory < ApplicationRecord
  self.table_name = 'search_categories'
  self.primary_key =  'sc_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def items
    @items_list = Item.all
  end

  def remote_ip
    if request.remote_ip == '127.0.0.1'
      # Hard coded remote address
      '123.45.67.89'
    else
      request.remote_ip
    end
  end

  def get_city(lat, long)
    Geokit::Geocoders::GoogleGeocoder.reverse_geocode "37.791821,-122.394679"

  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def index
    @client_ip = remote_ip()
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
    @glass_examples = Item.where({category: 'glass'})
    @plastic_examples = Item.where({category: 'plastic'})
    @papers_examples = Item.where({category: 'papers'})
    @metals_examples = Item.where({category: 'metals'})
    @chemicals_oil_examples = Item.where({category: 'chemicals/oil'})
    @hazardous_examples = Item.where({category: 'hazardous'})
    @electronics_examples = Item.where({category: 'electronics'})
    @ebl_examples = Item.where({category: 'ewaste/batteries/lights'})
    @organic_examples = Item.where({category: 'organic'})
    @bulk_examples = Item.where({category: 'bulk'})
    @pharmaceuticals_examples = Item.where({category: 'pharmaceuticals'})
    @mixed_examples = Item.where({category: 'mixed'})
    @other_examples = Item.where({category: 'other'})
  end

  def get_ajx
    all_items = Item.all()
    all_cats = Category.all()
    all_centers = RecyclingPlant.all()

    items_arr = Array.new

    all_items.each do |item|
      arr_item = Hash.new
      arr_item["category"] = item.category
      arr_item["name"] = item.name
      arr_item["item_id"] = item.item_id
      items_arr.push(arr_item)
    end

    all_cats.each do |cat|
      arr_item = Hash.new
      arr_item["name"] = cat.name
      arr_item["category_id"] = cat.category_id
      items_arr.push(arr_item)
    end

    all_centers.each do |center|
      arr_item = Hash.new
      arr_item["name"] = center.name
      arr_item["plant_id"] = center.plant_id
      arr_item["gps_coords"] = center.gps_coords
      items_arr.push(arr_item)
    end

    render :json => items_arr, :status => :ok
  end

  def get_ajx_item_infos
    all_items = Item.all()

    items_arr = Array.new

    all_items.each do |item|
      arr_item = Hash.new
      arr_item["info"] = item.info
      arr_item["item_id"] = item.item_id
      items_arr.push(arr_item)
    end

    render :json => items_arr, :status => :ok
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:text, :zip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_theme.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfolio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1 id="homeHeading">Your Favorite Source of Free Bootstrap Themes</h1>
            <hr>
            <p>Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
        </div>
    </div>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started!</a>
            </div>
        </div>
    </div>
</section>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
                    <h3>Sturdy Templates</h3>
                    <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
                    <h3>Ready to Ship</h3>
                    <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
                    <h3>Up to Date</h3>
                    <p class="text-muted">We update dependencies to keep things fresh.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
                    <h3>Made with Love</h3>
                    <p class="text-muted">You have to make your websites with love these days!</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter popup-gallery">
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/1.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/1.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/2.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/2.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/3.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/3.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/4.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/4.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/5.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/5.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/fullsize/6.jpg') %>" class="portfolio-box">
                    <img src="<%= image_path('startbootstrap-creative-gh-pages/img/portfolio/thumbnails/6.jpg') %>" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Download at Start Bootstrap!</h2>
            <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
        </div>
    </div>
</aside>

<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
                <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x sr-contact"></i>
                <p>123-456-6789</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/searches/_form.html.erb
<%= form_for(search) do |f| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<% provide(:page_title, "Edit @search.text)" %>


<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<% provide(:page_title, 'All posts') %>


<p id="notice"><%= notice %></p>

<h1>Searches</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Zip</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<% provide(:page_title, 'New post') %>


<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<% provide(:page_title, @search.text) %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @search.text %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @search.zip %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @search.slug %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>